Delete message
MarkLysenkoZp/messenger pull request #47
Opened 2022-10-18 10:44 UTC by Avialiner

2022-10-23 20:25 UTC, 1lyan commented
Решим конфликты. Потом я предложу улучшения по коду

2022-10-24 18:14 UTC, 1lyan commented on src/client/types.tsx
> +  messageId: string;
Просто id. "messageId" избыточно ведь сам интерфейс называется IDeletingMessage

2022-10-24 18:17 UTC, 1lyan commented on src/client/utils/chatUtils.ts
> +  const endpointUrl = '/api/delete_message/' + messageObj.messageId;
messageObj для передачи на сервер делаем в виде { id: 1, message: 'text' }

2022-10-24 18:17 UTC, 1lyan commented on src/client/utils/chatUtils.ts
> +    id: Number(messageObj.messageId),
messageObj.id

2022-10-24 18:19 UTC, 1lyan commented on src/client/utils/chatUtils.ts
> +    isDeleting: false,
Думаю, будет логично здесь сделать
```
isDeleting: true,
```

2022-10-24 18:21 UTC, 1lyan commented on src/client/Chat.tsx
> +  const [deletingMessage, setDeletingMessage] = useState({messageId: ''});
Предлагаю "deletedMessage" и "setDeletedMessage"

2022-10-24 18:22 UTC, 1lyan commented on src/client/Chat.tsx
> +  const [deletingMessage, setDeletingMessage] = useState({messageId: ''});
```
useState({id: ''});
```

2022-10-24 18:23 UTC, 1lyan commented on src/client/Chat.tsx
> +            isDeleting: msg.isDeleting,
Предлагаю
```
isDeleted
```

2022-10-24 18:25 UTC, 1lyan commented on src/client/ChatClient.tsx
> +  handleDeleteButton(messageId: string) {
```
id: string
```

2022-10-24 18:25 UTC, 1lyan commented on src/client/ChatClient.tsx
> +      messageId: messageId,
```
id: id
```

2022-10-24 18:25 UTC, 1lyan commented on src/client/ChatClient.tsx
> +      isDeleting: true,
```
isDeleted
```

2022-10-24 18:26 UTC, 1lyan commented on src/client/constants.tsx
> +  isDeleting: false,
```
isDeleted
```

2022-10-24 18:26 UTC, 1lyan commented on src/client/types.tsx
> +  isDeleting: boolean;
```
isDeleted
```

2022-10-24 18:26 UTC, 1lyan commented on src/client/types.tsx
> +  setDeletingMessage: Function;
```
SetDeletedMessage
```

2022-10-24 18:27 UTC, 1lyan commented on src/client/utils/chatUtils.ts
> +      isDeleting: m.isDeleting,
```
isDeleted: m.isDeleted,
```

2022-10-24 18:27 UTC, 1lyan commented on src/client/utils/chatUtils.ts
> +    isDeleting: false,
```
isDeleted: false,
```

2022-10-24 18:28 UTC, 1lyan commented on src/client/utils/chatUtils.ts
> +    setDeletingMessage: ()=>{}
setDeletedMessage

2022-10-24 18:29 UTC, 1lyan requested changes
@Avialiner, посмотри, пжлст. Но сначала реши конфликты

2022-10-24 18:31 UTC, 1lyan commented on src/client/Chat.tsx
> +    const list = messages.filter((m) => m.id !== message.id)
Дублируется со 114 строчкой

2022-10-24 18:32 UTC, 1lyan commented on src/client/Chat.tsx
> +            list = list.filter((message) => m.id !== message.id)
Дублируется с 61-й строчкой. Объединить, вынести в отдельный метод и повторно использовать

2022-10-24 20:07 UTC, Avialiner commented on src/client/ChatClient.tsx
> +      messageId: messageId,
В объекте msg уже есть id: this.clientID

2022-10-25 20:07 UTC, 1lyan commented on src/client/ChatClient.tsx
> +      messageId: messageId,
@Avialiner, я это поле переименовал в clientId вот тут https://github.com/1lyan/chat-transport/pull/1/files

2022-10-25 20:11 UTC, 1lyan commented on src/client/types.tsx
> +export interface IDeletingMessage {
@Avialiner, чуть не забыл. Чтобы быть последовательными предлагаю
```
IDeletedMessage
```

2022-10-29 08:05 UTC, 1lyan commented on src/client/Chat.tsx
> +            id: msg.messageId ? msg.messageId : msg.id,
У нас не будет атрибута messageId для message. Будет id - это идшник сообщения, и еще будет (уже есть) clientId - это идшник объекта connection на сервере сообщений

2022-10-29 08:06 UTC, 1lyan commented on src/client/ChatClient.tsx
> +      messageId: messageId,
У нас не будет атрибута messageId для message. Будет id - это идшник сообщения, и еще будет (уже есть) clientId - это идшник объекта connection на сервере сообщений

2022-10-29 08:06 UTC, 1lyan commented on src/client/ChatClient.tsx
> +      id: this.clientId,
clientId: clientId

2022-10-29 08:08 UTC, 1lyan commented on src/routes/api/deleteMessage.ts
> +    const result = await Message.destroy(
👍

2022-10-30 12:46 UTC, 1lyan approved these changes

2022-10-30 19:48 UTC, merged